dist: trusty

jobs:
  include:
    - stage: build docker image
      if: branch = master
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t api-gateway .
      - docker tag api-gateway $DOCKER_USERNAME/api-gateway
      - docker push $DOCKER_USERNAME/api-gateway